### PR TITLE
1023 topify strict mode

### PR DESCRIPTION
**Pull request by jaredhirsch**
@meandavejustice Mind taking a look? This fixes the mac topify behavior for me. (Do you have access to a mac?)

### CODE REVIEW

**Comment by 6a68** [comment]
@meandavejustice Added a commit which similarly deals with top-level 'this' global in the ostypes_x11 file. This might fix #1024, could you try it and see?

**Comment by meandavejustice** [comment]
@6a68 Just verified this is working in xfce on ubuntu

**Comment by meandavejustice** [comment]
I'd love to get this merged in the AM, when you get a moment, would you mind squashing these commits and removing the dependency commit? Those deps are child deps and should be installed by their parent dependencies.

**Comment by 6a68** [comment]
Sweet! Good timing. I just confirmed that this patch fixes #1024 on Nightly + Ubuntu 16.04 LTS with Unity window manager.

**Comment by 6a68** [comment]
@meandavejustice squashed, dep commit removed, good to land

**Pull request merged**
