### PR TITLE
Change deployment method

### PR DESCRIPTION
**Pull request by meandavejustice**
- add `deploy-txp` dependency
- cleanup npm scripts
- remove dist/ dir
- update .gitignore for new xpi output

### CODE REVIEW

**Comment by 6a68** [comment]
@meandavejustice If I run the following command:

```sh
$ TESTPILOT_AMO_USER=cheez TESTPILOT_AMO_SECRET=whiz npm run deploy
```

I don't get any error message:

```sh
JPM [info] Signing XPI: addon.xpi
```

**Comment by meandavejustice** [comment]
@6a68 fixed the unauthorized error handling here https://github.com/meandavejustice/deploy-txp/commit/5c111e8bb59464be3d812591bf778a9096a77b21

**Comment by 6a68** [comment]
@meandavejustice :+1: Yup, now seeing errors when the creds are bad, as well as a 403 when I try to submit min-vid using a random AMO account:

```sh
JPM [info] Signing XPI: addon.xpi
Server response: You do not own this addon. (status: 403)
```

I think the `deploy-txp` script should probably exit with a non-zero error code, though, if something's gone wrong. Good to land once that's done

**Comment by meandavejustice** [comment]
@6a68 fixed in deploy-txp version 1.0.5. Merged cus @clouserw asked about this this morning.

**Pull request merged**
