### PR TITLE
[WIP] Add support for `gaming.youtube.com`

### LINKED ISSUE #291: The context-menu option and the overlay icon are missing from gaming.youtube.com
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.9

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.9) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://gaming.youtube.com/.
2. Right-click or hover with the mouse on a video.

[Expected result]:
- Both the context-menu option and the video overlay icon are available on gaming.youtube.com

[Actual result]:
- Both the context-menu option and the video overlay icon are missing from gaming.youtube.com

[Notes]:
- After navigating to a video from gaming.youtube.com, the overlay icon is available only in the main video.
- Added a screen recording with the issue: https://goo.gl/EAW3GE
  issue_youtube_gaming

### PR DESCRIPTION
**Pull request by victorhqc**
Gaming Youtube has two main parts. A carousel in the main page, and the suggested videos. For the first, a new wrapper was needed to implement in order to show it. The carousel has a title and preview per video which is troublesome to remove, so instead the solution was to show the icon-overlay in the bottom.

screen shot 2017-08-29 at 11 54 43 am

For the second part, just a new selector was implemented, but it was placed in a new handler function called `ytGamingHandler`.

screen shot 2017-08-29 at 11 54 55 am

Fixes #291

### CODE REVIEW

**Comment by meandavejustice** [comment]
Great work! really happy to include this feature!

I removed the offending commit from #1021. Would you mind rebasing to get rid of that commit from your branch and squashing history into 1 commit. Thanks!

**Comment by victorhqc** [comment]
For sure! on it :)

**Comment by victorhqc** [comment]
Changes made. Removed last commit that broke plugin.

**Comment by victorhqc** [comment]
Waiting for https://github.com/meandavejustice/min-vid/pull/1026 to be merged. As it will generate some conflicts with this `PR`

**Pull request merged**
