### PR TITLE
Force ui update when video is paused and seeking

### LINKED ISSUE #259: Scrubber bar UI is not updated when selecting a custom position if the video is on pause
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to YouTube.
3. Send a video to the Min-Vid player and play the video.
4. Click near the end of the video in scrubber bar.
5. Put the video on pause.
6. Click near the start of the video in scrubber bar.

[Expected result]:
- Scrubber bar UI and video position are adjusted to the selected spot.

[Actual result]:
- Scrubber bar UI is not adjusted to the selected spot.

[Additional Notes]:
- This behaviour is observed only for video from YouTube.
- A video with the [scrubber issue](https://github.com/meandavejustice/min-vid/files/474383/scrubber.issue.zip) has been attached
- After this issue has happened, if we send another video to Min-Vid player and click on the scrubber bar the video will start but the play button will still be in "Play" state, scrubber UI and timecode will not update as time will elapse.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #259

### CODE REVIEW

**Comment by 6a68** [comment]
@meandavejustice This PR almost fixes it--the blue time slider isn't updated, but the freeze frame is. I'm guessing the entire UI should be updated to the specific clicked point in time.

**Comment by meandavejustice** [comment]
@6a68 hmm, I just testing this again, and it's working for me. Would you mind trying again and seeing if you are getting any errors? Not sure why something like this would be different on mac

**Comment by 6a68** [comment]
Sure, I'll give it another try.

**Comment by 6a68** [comment]
@meandavejustice This is so weird! The player seemed to be getting stuck flapping between play and pause after I dragged around the time slider a bit. I thought it was just jpm watchpost, but it persisted after killing watchpost and restarting (though I did use the same profile). After a second restart, it went away. I wonder if this is the bug where frame scripts get cached indefinitely.

Anyway, it now seems to work perfectly, so: merging :tada:

**Pull request merged**
