### PR TITLE
Disable panel autohide

### LINKED ISSUE #1: Ensure vid-view stays on top when switching tabs
Make sure the video view is not dismissed when interacting with page.

The current implementation uses `sdk/panel`. The default actions for this component mean it is dismissed with `<esc>` or body:click. We need to do some research and see what type of component we should use instead.

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #1.

@meandavejustice mind taking a look? this solves the problem of the panel autohiding itself, but introduces the problem that you can't get rid of the panel. :-)

The fix is to call panel.hide(), I'm just not yet sure how we can add a button to the panel / style the panel.

### CODE REVIEW

**Comment by 6a68** [comment]
Hmm, I think I'm unlocking some XUL secrets. Don't merge this just yet.

**Comment by 6a68** [comment]
Ah, never mind, I guess I"ll have to fix closing and moving the panel in a separate PR. `backdrag=true` seems to be the attribute used by XUL to make an element draggable, but for some reason it's not working in this case. Not sure why.

**Comment by meandavejustice** [comment]
I address this in #15. I also tested the backdrag, and I wasn't able to get it work either.

**Comment by meandavejustice** [comment]
Thank you!

**Pull request merged**
