### PR TITLE
Add basic support for Soundcloud playlist

### PR DESCRIPTION
**Pull request by NearTox**

### CODE REVIEW

**Comment by meandavejustice** [comment]
Hey @NearTox I apologize for the delay on feedback. I really appreciate the contribution. I should have time to review tomorrow morning :)

**Comment by NearTox** [comment]
Hello @meandavejustice I apologize for the delay on response
to launch a playlist its the same process that a normal track:
pass the mouse across the artwork of the set(playlist)
example of an url:
https://soundcloud.com/nasa/sets/juno-spacecraft

**Comment by NearTox** [comment]
fixes made with https://github.com/meandavejustice/audiosource#7:
https://github.com/meandavejustice/min-vid/issues/771
https://github.com/meandavejustice/min-vid/issues/899
https://github.com/meandavejustice/min-vid/issues/882

potential fixes:
https://github.com/meandavejustice/min-vid/issues/882

**Comment by meandavejustice** [comment]
Thanks @NearTox, this works great! it'll be included in the next release( which should be sometime next week) :)

**Pull request merged**
