### PR TITLE
Save the window's location when it's minimized, maximized, or dropped

### LINKED ISSUE #503: The custom position for Min-Vid player is not remembered
[Notes]:
- Based on https://github.com/meandavejustice/min-vid/pull/475#issuecomment-259465554

[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.3.3-dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.3-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com.
2. Send a video to the mini player using the thumbnail overlay or context menu.
3. Move the mini player to a new position and close it.
4. Repeat step 2 and observe the mini player's position.

[Expected result]:
- The mini player is placed in the same position as before it was closed.

[Actual result]:
- The mini player is placed in the top left corner of the screen.

[Additional Notes]:
- Attached a screen recording of the issue: 
minvid_position_issue

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #503.

### CODE REVIEW

**Comment by 6a68** [comment]
I have not tested this on windows or linux yet. Working on that now.

**Comment by 6a68** [comment]
works fine on windows

**Comment by meandavejustice** [comment]
@6a68 Would you mind adding some code to cleanup this object from simple storage onUnload if we are uninstalling? Probably in the `windowUtils.destroy` method

**Comment by 6a68** [comment]
@meandavejustice great point, I'll add that now

**Pull request merged**
