### PR TITLE
Add certain controls while loading

### LINKED ISSUE #78: allow certain controls while loading
If you are on a slow connection, you may want to just close instead of waiting for the video to load. (i'm on public wifi rn and this is annoying)

~~* close~~
* min/max
* mute
* send to tab?

### PR DESCRIPTION
**Pull request by kaganjd**
Fixes #78.

### CODE REVIEW

**Comment by kaganjd** [comment]
I couldn't replicate slow internet so couldn't test, but added these controls the same way `close` button appears to work in LoadingView. Let me know what if this needs any changes.

**Comment by meandavejustice** [comment]
The buttons still need to be added into the `render` method. Try testing by running a localserver and going to http:localhost:8080/data/default.html to make sure they are showing up.

**Comment by kaganjd** [comment]
Needs "send-to-tab" handling and bug with "maximize". Will be fixed in #106

**Comment by meandavejustice** [comment]
Thanks!

**Pull request merged**
